version: "3"
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        command: php artisan serve --host=0.0.0.0 --port=8000
        image: laravel-app
        container_name: backend
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: backend
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - myapp-network

networks:
    myapp-network:
        external: true
